name: precis
description: An implementation of the PRECIS Language Rules as defined by RFC 8265
version: 0.0.3
homepage:
repository: https://github.com/flutter-institute/precis
issue_tracker: https://github.com/flutter-institute/precis/issues

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  characters: ^1.2.0
  meta: ^1.7.0
  unorm_dart: ^0.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
